services:
  api:
    image: mparchin/dnd-api:${DOTNET_ENVIRONMENT}
    build: .
    container_name: dnd-api
    profiles:
      - app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80

  postgres:
    profiles:
      - db
      - app
    image: registry.docker.ir/postgres:16.0-alpine3.18
    container_name: dnd-postgres
    environment:
      - POSTGRES_PASSWORD=${Postgres_Password}
      - POSTGRES_USER=${Postgres_User}
      - POSTGRES_DB=${Postgres_Db}
    volumes:
      - dnd-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  dnd-postgres:
